// Autogenerated C file from asterisk-cartographer utility
// Built on 2018-02-06 20:48:06

#include "main.h"
#include <stdio.h>

#define NUM_MAPS 1

#define NUM_WATER_TEX 3
#define NUM_VEGETATION_TEX 5
#define NUM_MACHINERY_TEX 10
#define NUM_OVER_MACHINERY_TEX 4
#define NUM_FIRE_TEX 3

entity_t null_entities_list[4] = { {0, 7, 7, 2}, {0, 7, 8, 3}, {0, 7, 9, 4}, {0, 7, 10, 1} };

// GENERATED MAP example_map_0
int example_map_0_map_data[] = {12, 0, 12, 0, 0, 8, 2, 2, 0, 0,
12, 12, 12, 4, 4, 4, 4, 4, 11, 0,
0, 1, 1, 1, 1, 1, 1, 1, 3, 2,
0, 0, 0, 0, 0, 0, 0, 0, 2, 2,
0, 5, 6, 0, 6, 6, 6, 6, 9, 10,
0, 7, 0, 6, 6, 0, 0, 6, 10, 10,
0, 0, 0, 0, 0, 0, 0, 0, 10, 2,
0, 1, 1, 1, 1, 1, 1, 1, 1, 10,
0, 4, 4, 4, 4, 4, 4, 4, 4, 2,
0, 0, 0, 0, 0, 32, 0, 0, 2, 0,
0};
map_t example_map_0_map = {10, 10,example_map_0_map_data , 0, null_entities_list};
coord_t example_map_0_start = {1, 4};
npc_t example_map_0_npc ( unsigned int x, unsigned int y ){
    npc_t npc_null = {-1, 0, 0, 0, {-1, 0, ' ', 0}, false, false, false, 0, -1, -1 };
    npc_t npc_0 = {112, 1000, 0, 2, {{17, 10, " ", 0, 140}, {18, 2, " ", 0, 70}}, true, false, true, 0, 8, 4};

    if( x == 8 && y == 4 ) return npc_0;

    return npc_null;
}
portal_t example_map_0_portal( unsigned int x, unsigned int y ){
    portal_t portal_null = {0, 0, -1};
    portal_t portal_0 = {1, 0, 0 };
    if ( x == 1 && y == 5 ) return portal_0;
    return portal_null;
}

int master_index = 0;
map_t cached_map;
map_master rogue_map_master[NUM_MAPS];
npc_function_ft rogue_npc_master[NUM_MAPS];
portal_function_ft rogue_portal_master[NUM_MAPS];

void init_maps(){
    rogue_map_master[0] = (map_master) { example_map_0_map, example_map_0_start };
    rogue_npc_master[0] = example_map_0_npc;
    rogue_portal_master[0] = example_map_0_portal;
}

void load_map(int index){
    master_index = index;
    cached_map = rogue_map_master[index].mapdat;
    character_x = rogue_map_master[index].coord.x;
    character_y = rogue_map_master[index].coord.y;
    cached_map.num_entities = rogue_map_master[index].mapdat.num_entities;
    num_entities = rogue_map_master[index].mapdat.num_entities;
    printf("Loading map %d with start of (%d, %d) and %d entities \n", index, rogue_map_master[index].coord.x, rogue_map_master[index].coord.y, rogue_map_master[index].mapdat.num_entities);
    for (int i = 0; i < rogue_map_master[index].mapdat.num_entities; i++){
        entities[i] = rogue_map_master[index].mapdat.entities[i];
    }
}
