// Autogenerated C file from asterisk-cartographer utility
// Built on 2018-06-07 23:27:05


#include "main.h"
/* #define NUM_QUESTS_MAX 1*/
/* #define QUEST_STR_DAT_LEN 152*/

char quest_str_dat [ QUEST_STR_DAT_LEN ] = 
    #include "quest_string.dat"
;
// Quest #0 : Test_Quest
int quest_0_data[] = {0,-1,-1,-1,6,0,-1};
int quest_0_verify[] = {0,0,0,0,0,0,0};
int quest_0_action[] = {0,0,0,0,0,0,0};
int quest_0_bmp[] = {5,5,3,2,4,5,1};
int quest_0_text[] = {0,6,25,30,41,72,3};
mquest_t quest_0 = {1,
    "Test_Issuer",
    "Test_Quest",
    6,
    1000,
    5000,
    {14332, 5, false, 1},
    quest_0_data,
    quest_0_verify,
    quest_0_action,
    quest_0_bmp,
    quest_0_text};

mquest_t quest_registry[ NUM_QUESTS_MAX + 1];
int num_active_quests;
mquest_a_t quest_a_registry[ NUM_QUESTS_MAX + 1];
quest_validate_function_ft quest_validate_master[NUM_QUESTS_MAX + 1];
quest_action_function_ft quest_action_master [NUM_QUESTS_MAX + 1];
cutscene_t cutscene_registry[NUM_CUTSCENES];
extern int quests_consumed[NUM_QUESTS_MAX];

int cutscene_0_delays[4] = {1000, 1000, 2000, 50};
int cutscene_0_text[4] = {0, 5, 10, 15};
cutscene_t cutscene_0 = {1, 4, 0, cutscene_0_delays, 0, cutscene_0_text};

void init_cutscenes(){
    cutscene_registry[0] = cutscene_0;
}
void init_quests(){
    quest_registry[1] = quest_0;
}